name: Dev-to-Prod
'on': push
#  push:
#    branches:
#      - dev
jobs:
  copy-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --global user.name "amandoriki"
          git config --global user.email "amandoriki92@yahoo.com"
      - name: Fetch all branches
        run: git fetch --all
      - name: Checkout dev
        run: git checkout dev
      - name: Copy content from dev
        run: |
          git pull origin dev  # Ensure you have the latest changes
          cp -r . ../dev-content  # Copy content to a temporary location
      - name: Checkout prod
        run: |
          git checkout prod
          git pull origin prod
      - name: Copy content to prod
        run: >
          cp -r ../dev-content/* .  # Copy content from the temporary location
          to branch-2

          git add .

          git commit -m "Sync content from dev to prod"
      - name: Push changes to prod
        run: git push origin prod
        env:
          GITHUB_TOKEN: ${ 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 }  # Use the GitHub token to push changes
